In [1]:
import numpy as np
import pandas as pd

In [2]:
ddos = pd.read_csv('DDos_2m.csv')

In [3]:
ddos.columns

Index(['Unnamed: 0', 'FlowDuration', 'TotalFwdPackets', 'TotalBackwardPackets',
       'TotalLengthofFwdPackets', 'TotalLengthofBwdPackets',
       'FwdPacketLengthMax', 'FwdPacketLengthMin', 'FwdPacketLengthMean',
       'FwdPacketLengthStd', 'BwdPacketLengthMax', 'BwdPacketLengthMin',
       'BwdPacketLengthMean', 'BwdPacketLengthStd', 'FlowBytes/s',
       'FlowPackets/s', 'FlowIATMean', 'FlowIATStd', 'FlowIATMax',
       'FlowIATMin', 'FwdIATTotal', 'FwdIATMean', 'FwdIATStd', 'FwdIATMax',
       'FwdIATMin', 'BwdIATTotal', 'BwdIATMean', 'BwdIATStd', 'BwdIATMax',
       'BwdIATMin', 'FwdPSHFlags', 'BwdPSHFlags', 'FwdURGFlags', 'BwdURGFlags',
       'FwdHeaderLength', 'BwdHeaderLength', 'FwdPackets/s', 'BwdPackets/s',
       'MinPacketLength', 'MaxPacketLength', 'PacketLengthMean',
       'PacketLengthStd', 'PacketLengthVariance', 'FINFlagCount',
       'SYNFlagCount', 'RSTFlagCount', 'PSHFlagCount', 'ACKFlagCount',
       'URGFlagCount', 'CWEFlagCount', 'ECEFlagCount', 'Down/UpRatio

In [4]:
ddos = ddos.drop(columns = ['Unnamed: 0'])

In [5]:
ddos.shape

(2011542, 78)

In [11]:
ddos['Label'].value_counts()

2    578745
5    428475
6    375468
3    365749
1    191512
0     52897
4     18696
Name: Label, dtype: int64

In [10]:
df = ddos.copy()
cat_columns = df.select_dtypes(['object']).columns
cat_columns

Index([], dtype='object')

In [8]:
df[cat_columns] = df[cat_columns].astype('category')
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
df
ddos = df
ddos.dtypes

FlowDuration               float64
TotalFwdPackets            float64
TotalBackwardPackets       float64
TotalLengthofFwdPackets    float64
TotalLengthofBwdPackets    float64
                            ...   
IdleMean                   float64
IdleStd                    float64
IdleMax                    float64
IdleMin                    float64
Label                         int8
Length: 78, dtype: object

In [9]:
X = ddos.iloc[:, 0:-1]
y = ddos.iloc[:, -1]

In [10]:
ddos = None; del ddos

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [12]:
X_train.to_csv('X_train_2m.csv')

In [12]:
X_test['Label'] = Y_test

C:\Users\LabUser\AppData\Local\Temp/ipykernel_10812/3922236013.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Label'] = Y_test


In [21]:
np.bincount(y)

array([ 52897, 190383, 575334, 363594,  18585, 425949, 373255],
      dtype=int64)

In [13]:
part2 = pd.read_csv('DDos_17m.csv')

In [14]:
part2 = part2.drop(['Unnamed: 0'],axis = 1)

In [15]:
part2['Label'].value_counts()

MSSQL      5208708
Syn        3856276
UDP        3379212
NetBIOS    3291748
LDAP       1723610
Portmap     168264
Name: Label, dtype: int64

In [16]:
part2['Label'].replace('LDAP',1,inplace = True)
part2['Label'].replace('MSSQL',2,inplace = True)
part2['Label'].replace('NetBIOS',3,inplace = True)
part2['Label'].replace('Portmap',4,inplace = True)
part2['Label'].replace('Syn',5,inplace = True)
part2['Label'].replace('UDP',6,inplace = True)

In [17]:
testing = pd.concat([X_test,part2])

In [18]:
part2 = None; del part2

In [21]:
testing['Label'].value_counts()

2    5398127
5    3997030
6    3502471
3    3411891
1    1786437
4     174362
0      17500
Name: Label, dtype: int64

In [22]:
testing['Label'].replace(0,10,inplace = True)
testing['Label'].replace(1,11,inplace = True)
testing['Label'].replace(2,12,inplace = True)
testing['Label'].replace(3,13,inplace = True)
testing['Label'].replace(4,14,inplace = True)
testing['Label'].replace(5,15,inplace = True)
testing['Label'].replace(6,16,inplace = True)

In [23]:
testing['Label'].value_counts()

12    5398127
15    3997030
16    3502471
13    3411891
11    1786437
14     174362
10      17500
Name: Label, dtype: int64

In [24]:
testing['Label'].replace(10,0,inplace = True)
testing['Label'].replace(11,1,inplace = True)
testing['Label'].replace(12,2,inplace = True)
testing['Label'].replace(13,3,inplace = True)
testing['Label'].replace(14,4,inplace = True)
testing['Label'].replace(15,5,inplace = True)
testing['Label'].replace(16,6,inplace = True)

In [25]:
X_test = testing.drop(['Label'],axis= 1)
Y_test = testing['Label']

In [13]:
X_train.shape

(1347733, 77)

In [14]:
Y_train.shape

(1347733,)

In [15]:
X_test.shape

(663809, 77)

In [16]:
Y_test.shape

(663809,)

In [30]:
testing = None; del testing

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
from keras.utils import np_utils
X_train=np.expand_dims(X_train,axis=2)
X_test=np.expand_dims(X_test,axis=2)

In [19]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(77,1)))
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(7, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [56]:
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(77,1)))
model.add(Dropout(0.92))
model.add(MaxPooling1D(pool_size=2,strides=1, padding='valid'))
model.add(Flatten())
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 1 epoch

In [57]:
from keras.callbacks import EarlyStopping
import time

start = time.time()
print("Timer Begin")

model.fit(X_train,Y_train,batch_size=30,epochs=1,
          validation_split=0, callbacks=[EarlyStopping(monitor='loss',patience=2)])

end = time.time()
print(end - start)

Timer Begin
44925/44925 [==============================] - 148s 3ms/step - loss: 0.1827 - accuracy: 0.94350s
148.37553691864014


# small test

In [58]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [59]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[ 17155      0      0    220      0    125      4]
 [     1  62555    499      8      0      5      1]
 [     7   6650 183712     22      2      3   1092]
 [     0      0     21 120269      0     11     85]
 [     5      0     25   6108      0     21      5]
 [   159      0    138      1      0 141057     20]
 [     0      1  16677    147      0      2 106996]]


In [60]:
CR = classification_report(Y_test,y_pred,digits= 4)
print(CR)

              precision    recall  f1-score   support

           0     0.9901    0.9801    0.9850     17504
           1     0.9039    0.9919    0.9458     63069
           2     0.9137    0.9594    0.9360    191488
           3     0.9487    0.9990    0.9732    120386
           4     0.0000    0.0000    0.0000      6164
           5     0.9988    0.9978    0.9983    141375
           6     0.9888    0.8641    0.9223    123823

    accuracy                         0.9517    663809
   macro avg     0.8206    0.8275    0.8229    663809
weighted avg     0.9448    0.9517    0.9470    663809



# large test

In [37]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [38]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[  17373       0       5      51       0      71       0]
 [     74 1767224   18727     284       0     122       6]
 [    332  123828 5156456     277       0     112  117122]
 [    377       3     763 3405805       0      77    4866]
 [    343       0     757  172853       0     182     227]
 [   2468       0    4063    1280       0 3988574     645]
 [     50       0   73162     328       0      46 3428885]]


In [39]:
CR = classification_report(Y_test,y_pred,digits= 4)
print(CR)

C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0     0.8266    0.9927    0.9021     17500
           1     0.9345    0.9892    0.9611   1786437
           2     0.9814    0.9552    0.9682   5398127
           3     0.9511    0.9982    0.9741   3411891
           4     0.0000    0.0000    0.0000    174362
           5     0.9998    0.9979    0.9989   3997030
           6     0.9654    0.9790    0.9722   3502471

    accuracy                         0.9714  18287818
   macro avg     0.8084    0.8446    0.8252  18287818
weighted avg     0.9626    0.9714    0.9668  18287818



C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# epoch 2

In [40]:
from keras.callbacks import EarlyStopping
import time

start = time.time()
print("Timer Begin")

model.fit(X_train,Y_train,batch_size=30,epochs=1,
          validation_split=0, callbacks=[EarlyStopping(monitor='loss',patience=2)])

end = time.time()
print(end - start)

Timer Begin
44667/44667 [==============================] - 387s 9ms/step - loss: 0.1106 - accuracy: 0.9704
389.8259468078613


# small test

In [22]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [23]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[ 17373      0      5     34      1     76     15]
 [     1  61970   1084      8      0      5      1]
 [     9   4196 184342     18      0      5   2918]
 [    15      0     21 120174      0      2    174]
 [    14      0     25   6098      4     13     10]
 [    79      0    135      1      0 141137     23]
 [     1      0   2656     10      0      1 121155]]


In [24]:
CR = classification_report(Y_test,y_pred, digits= 4)
print(CR)

              precision    recall  f1-score   support

           0     0.9932    0.9925    0.9929     17504
           1     0.9366    0.9826    0.9590     63069
           2     0.9791    0.9627    0.9708    191488
           3     0.9512    0.9982    0.9741    120386
           4     0.8000    0.0006    0.0013      6164
           5     0.9993    0.9983    0.9988    141375
           6     0.9747    0.9785    0.9766    123823

    accuracy                         0.9734    663809
   macro avg     0.9477    0.8448    0.8391    663809
weighted avg     0.9722    0.9734    0.9689    663809



# large test

In [41]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [42]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[  17448       0       0      25       0      27       0]
 [    109 1768144   17803     284       0      95       2]
 [    397  164288 5032455     222       0     102  200663]
 [    374       3     780 3403470       0      79    7185]
 [    337       0     750  172705       0     194     376]
 [   2784       0    4054      28       0 3989519     645]
 [     46       3   67578     226       0      42 3434576]]


In [43]:
CR = classification_report(Y_test,y_pred, digits= 4)
print(CR)

C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0     0.8117    0.9970    0.8949     17500
           1     0.9150    0.9898    0.9509   1786437
           2     0.9822    0.9323    0.9566   5398127
           3     0.9515    0.9975    0.9740   3411891
           4     0.0000    0.0000    0.0000    174362
           5     0.9999    0.9981    0.9990   3997030
           6     0.9427    0.9806    0.9613   3502471

    accuracy                         0.9649  18287818
   macro avg     0.8004    0.8422    0.8195  18287818
weighted avg     0.9567    0.9649    0.9603  18287818



C:\Users\LabUser\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 3 epoch

In [44]:
from keras.callbacks import EarlyStopping
import time

start = time.time()
print("Timer Begin")

model.fit(X_train,Y_train,batch_size=30,epochs=1,
          validation_split=0, callbacks=[EarlyStopping(monitor='loss',patience=2)])

end = time.time()
print(end - start)

Timer Begin
44667/44667 [==============================] - 506s 11ms/step - loss: 0.1102 - accuracy: 0.9711
509.62669920921326


# small test

In [26]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [27]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[ 17421      0      0     69      3     10      1]
 [     0  62313    743      8      2      3      0]
 [     9   4306 180142     21      1      3   7006]
 [    12      0     21 120116      0      2    235]
 [    14      0     25   5782    328      3     12]
 [   139      0    135      1     40 141037     23]
 [     1      0   2630      9      1      0 121182]]


In [28]:
CR = classification_report(Y_test,y_pred, digits= 4)
print(CR)

              precision    recall  f1-score   support

           0     0.9901    0.9953    0.9926     17504
           1     0.9354    0.9880    0.9610     63069
           2     0.9807    0.9407    0.9603    191488
           3     0.9533    0.9978    0.9750    120386
           4     0.8747    0.0532    0.1003      6164
           5     0.9999    0.9976    0.9987    141375
           6     0.9434    0.9787    0.9607    123823

    accuracy                         0.9680    663809
   macro avg     0.9539    0.8502    0.8498    663809
weighted avg     0.9678    0.9680    0.9641    663809



# large test

In [45]:
y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

In [46]:
rf_conf_mat = confusion_matrix(Y_test, y_pred)
print("Transfer learning confusion matrix: \n", rf_conf_mat)

Transfer learning confusion matrix: 
 [[  17359       1       0      70       3      60       7]
 [     50 1766327   19615     330       0     104      11]
 [    290  119735 5194422     353       0      40   83287]
 [    136       3     755 3403781       0      30    7186]
 [    123       0     750  173055       0      63     371]
 [   2526       0    4055    1169       0 3988635     645]
 [     54       1   73177     260       0       8 3428971]]


In [47]:
CR = classification_report(Y_test,y_pred, digits= 4)
print(CR)

              precision    recall  f1-score   support

           0     0.8452    0.9919    0.9127     17500
           1     0.9365    0.9887    0.9619   1786437
           2     0.9814    0.9623    0.9717   5398127
           3     0.9510    0.9976    0.9738   3411891
           4     0.0000    0.0000    0.0000    174362
           5     0.9999    0.9979    0.9989   3997030
           6     0.9740    0.9790    0.9765   3502471

    accuracy                         0.9733  18287818
   macro avg     0.8126    0.8454    0.8279  18287818
weighted avg     0.9645    0.9733    0.9687  18287818

